[
{
"cve_id": "CVE-2023-40017",
"patch_date": [
"2023-08-23 17:32:13+02:00"
],
"patch_files": [
"requirements.txt",
"geonode/proxy/tests.py",
"geonode/proxy/views.py",
"geonode/utils.py",
"setup.cfg"
],
"earliest_patch_date": "2023-08-23 17:32:13+02:00",
"earliest_vuln_date": "2023-01-23 19:14:32+01:00",
"vuln_files": [
"geonode/proxy/views.py"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "NONE",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "HIGH",
"integrityImpact": "NONE",
"availabilityImpact": "NONE",
"baseScore": 7.5,
"baseSeverity": "HIGH"
},
"exploitabilityScore": 3.9,
"impactScore": 3.6
}
},
"cwes": [],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2023-42439",
"patch_date": [
"2023-09-14 13:17:12+02:00"
],
"patch_files": [
"geonode/utils.py",
"geonode/proxy/tests.py"
],
"earliest_patch_date": "2023-09-14 13:17:12+02:00",
"earliest_vuln_date": "2023-08-23 17:32:13+02:00",
"vuln_files": [
"geonode/utils.py"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "LOW",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "HIGH",
"integrityImpact": "NONE",
"availabilityImpact": "NONE",
"baseScore": 6.5,
"baseSeverity": "MEDIUM"
},
"exploitabilityScore": 2.8,
"impactScore": 3.6
}
},
"cwes": [],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": true,
"files_fixed_before_fixed_again": [
"geonode/utils.py",
"geonode/proxy/tests.py"
],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
},
{
"cve_id": "CVE-2024-27091",
"patch_date": [
"2024-02-13 18:27:06+01:00"
],
"patch_files": [
"geonode/base/templatetags/sanitize_html.py",
"requirements.txt",
"geonode/templates/metadata_detail.html",
"setup.cfg",
"geonode/base/tests.py"
],
"earliest_patch_date": "2024-02-13 18:27:06+01:00",
"earliest_vuln_date": "2020-11-11 19:48:04+01:00",
"vuln_files": [
"geonode/templates/metadata_detail.html"
],
"impact": {},
"cwes": [],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": true,
"files_fixed_before_fixed_again": [
"requirements.txt",
"setup.cfg"
],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
}
]