[
{
"cve_id": "CVE-2023-41048",
"patch_date": [
"2023-09-21 13:22:31+02:00",
"2023-09-21 13:22:31+02:00",
"2023-09-21 13:22:31+02:00",
"2023-09-21 13:22:31+02:00"
],
"patch_files": [
"plone/namedfile/scaling.py",
"plone/namedfile/tests/test_display_file.py",
"news/1.bugfix"
],
"earliest_patch_date": "2023-09-21 13:22:31+02:00",
"earliest_vuln_date": "None",
"vuln_files": [],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "LOW",
"userInteraction": "REQUIRED",
"scope": "CHANGED",
"confidentialityImpact": "LOW",
"integrityImpact": "LOW",
"availabilityImpact": "NONE",
"baseScore": 5.4,
"baseSeverity": "MEDIUM"
},
"exploitabilityScore": 2.3,
"impactScore": 2.7
}
},
"cwes": [
"CWE-79"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
}
]