[
{
"cve_id": "CVE-2022-0336",
"patch_date": [
"2022-01-31 15:27:37+00:00",
"2022-01-31 15:27:37+00:00"
],
"patch_files": [
"source4/dsdb/samdb/ldb_modules/samldb.c",
"selftest/knownfail.d/ldap_spn",
"python/samba/tests/ldap_spn.py"
],
"earliest_patch_date": "2022-01-31 15:27:37+00:00",
"earliest_vuln_date": "2021-11-09 19:45:33+00:00",
"vuln_files": [
"source4/dsdb/samdb/ldb_modules/samldb.c",
"selftest/knownfail.d/ldap_spn"
],
"impact": {
"baseMetricV3": {
"cvssV3": {
"version": "3.1",
"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
"attackVector": "NETWORK",
"attackComplexity": "LOW",
"privilegesRequired": "LOW",
"userInteraction": "NONE",
"scope": "UNCHANGED",
"confidentialityImpact": "HIGH",
"integrityImpact": "HIGH",
"availabilityImpact": "HIGH",
"baseScore": 8.8,
"baseSeverity": "HIGH"
},
"exploitabilityScore": 2.8,
"impactScore": 5.9
}
},
"cwes": [
"CWE-276"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
}
]