[
{
"cve_id": "CVE-2011-3211",
"patch_date": [
"2011-08-11 12:41:16-04:00",
"2011-08-05 08:24:22-04:00"
],
"patch_files": [
"src/lib/Server/Plugins/Cfg.py",
"src/lib/Server/Admin/Viz.py",
"src/lib/Server/Plugins/Hg.py",
"src/lib/Server/Plugins/SSHbase.py",
"src/lib/Server/Plugins/SSLCA.py",
"src/lib/Server/Plugins/Svn.py"
],
"earliest_patch_date": "2011-08-05 08:24:22-04:00",
"earliest_vuln_date": "2006-04-25 21:03:18+00:00",
"vuln_files": [
"src/lib/Server/Plugins/Cfg.py",
"src/lib/Server/Admin/Viz.py",
"src/lib/Server/Plugins/Hg.py",
"src/lib/Server/Plugins/SSHbase.py",
"src/lib/Server/Plugins/Svn.py",
"src/lib/Server/Plugins/SSLCA.py"
],
"impact": {
"baseMetricV2": {
"cvssV2": {
"version": "2.0",
"vectorString": "AV:N/AC:M/Au:N/C:C/I:C/A:C",
"accessVector": "NETWORK",
"accessComplexity": "MEDIUM",
"authentication": "NONE",
"confidentialityImpact": "COMPLETE",
"integrityImpact": "COMPLETE",
"availabilityImpact": "COMPLETE",
"baseScore": 9.3
},
"severity": "HIGH",
"exploitabilityScore": 8.6,
"impactScore": 10,
"obtainAllPrivilege": false,
"obtainUserPrivilege": false,
"obtainOtherPrivilege": false,
"userInteractionRequired": false
}
},
"cwes": [
"CWE-20"
],
"fix_duplicate_type": false,
"fix_duplicate_types": [],
"intro_duplicate_type": false,
"intro_duplicated_types": [],
"file_fixed_before_fixed_again": false,
"files_fixed_before_fixed_again": [],
"file_fixed_before_vuln_again": false,
"files_fixed_before_vuln_again": []
}
]